### ISSUE TITLE
Conflict jquery ???

### ISSUE THREAD

**Issue by levanlau** [kartik-v/yii2-markdown#21]
Hi,
As i have used markdown in ActiveForm as following:
echo $form->field($modelCommentProduct, 'comment')->widget(
        MarkdownEditor::classname(), 
        ['height' => 300, 'encodeLabels' => false]
    );
and in browser console display an error:
Uncaught TypeError: undefined is not a function 
initEditor
(anonymous function) 
jQuery.event.dispatch
elemData.handle

I can not click up any place on markdown editor.
Could you please explain me this?Thanks.

**Comment by edvardpotter** [comment]
I also get a similar error: https://stackoverflow.com/questions/37738732/jquery-3-0-url-indexof-error
How can I fix this?
