### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by kangqf** [kartik-v/yii2-markdown#27]
when i press the preview button ,it comes loading preview  the error show 400 Bad Request 
send    @   jquery.js:8623
jQuery.extend.ajax  @   jquery.js:8152
togglePreview   @   kv-markdown.js:86
(anonymous function)    @   kv-markdown.js:357
jQuery.event.dispatch   @   jquery.js:4409
elemData.handle @   jquery.js:4095

**Comment by akorinek** [comment]
How do I add the _csrf? I couldn't find this in the documentation and get the same error. Webtip doesn't help, the Html::csrfMetaTags() are in the view, but it still doesn't work. Usually I add a hidden _csrf field to the form I'm submitting via ajax, but in this case there is no form.
