### ISSUE TITLE
Full screen, preview, and export buttons don't work

### ISSUE THREAD

**Issue by amnah** [kartik-v/yii2-markdown#30]
These three buttons don't seem to work, but everything else does (bold italics etc). 

No javascript errors in console.

Fresh installation:

1) composer.json `"kartik-v/yii2-markdown": "dev-master"`
2) add module `'markdown' => [ 'class' => 'kartik\markdown\Module' ]`
3) add to view

``` php
    <?=  MarkdownEditor::widget([
        'model' => $model,
        'attribute' => 'text',
    ]) ?>
```

**Comment by derekisbusy** [comment]
I have fixed this issue in my branch...

https://github.com/derekisbusy/yii2-markdown/pull/1/commits
