### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by gmstas** [kartik-v/yii2-markdown#35]
Hi i keep encountering the following when i try to install package:

 Problem 1
    - Installation request for kartik-v/yii2-markdown dev-master -> satisfiable by kartik-v/yii2-markdown[dev-master].
    - kartik-v/yii2-markdown dev-master requires michelf/php-smartypants * -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Can you assist please?

**Comment by kartik-v** [comment]
Depending on your application settings for composer -- you may need to read and understand about composer package dependencies and stability. You can read this [web tip](http://webtips.krajee.com/setting-composer-minimum-stability-application/) for understanding setting minimum stability. 

You can add the following line to your require section of composer json
```js
michelf/php-smartypants: '@dev'
```

**Comment by gmstas** [comment]
Thanks! works now
