### ISSUE TITLE
Install error!

### ISSUE THREAD

**Issue by dungphanxuan** [kartik-v/yii2-markdown#40]
Hello, i install package and receive error!
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for kartik-v/yii2-markdown dev-master -> satisfiable
by kartik-v/yii2-markdown[dev-master].
    - kartik-v/yii2-markdown dev-master requires michelf/php-smartypants * -> no
 matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common
 problems.

**Comment by str2code** [comment]
+1，me too

**Comment by str2code** [comment]
+1，me too

**Comment by str2code** [comment]
+1，me too

**Comment by kartik-v** [comment]
set your minimum-stability to dev in your composer json...

**Comment by kartik-v** [comment]
you need to study more about managing this within your composer settings in your application's composer.json file... for example the `michelf/php-smartypants` dependency is not getting installed on your environment... you need to check that...

One way for example is to set your minimum-stability to dev in your composer json...
