### ISSUE TITLE
No support for checkboxes / tasklist

### ISSUE THREAD

**Issue by WadeShuler** [kartik-v/yii2-markdown#42]
I am trying to get a simple todo list for the project I am on. Just to keep orderly, and for the client to see. Once in production, it would be removed..

I am looking for GitHub based markdown. ie: anything we can do on GitHub, we should be able to do with a markdown extension that "supports" GitHub.

    - [x] checked
    - [ ] unchecked

These seem to be unsupported by your extension.

**Comment by kartik-v** [comment]
It depends currently on PHP Markdown Extra Library and whatever it supports. 

Will update later in case I can add other libraries.
