### ISSUE TITLE
Composer Error

### ISSUE THREAD

**Issue by itconcept** [kartik-v/yii2-markdown#47]
Problem 1
    - Installation request for kartik-v/yii2-markdown dev-master -> satisfiable by kartik-v/yii2-markdown[dev-master].
    - kartik-v/yii2-markdown dev-master requires michelf/php-smartypants \* -> no matching package found.

**Comment by MetaCrawler** [comment]
Already Reportet - see:
https://github.com/kartik-v/yii2-markdown/issues/37
