### ISSUE TITLE
Generate a markdown TOC (table of contents) 

### ISSUE THREAD

**Issue by G1K** [kartik-v/yii2-markdown#54]
If this feature is very useful feature [TOC] which would generate a table of contents for headers. And to add a header parser is similar to hash on github #

[TOC]
- [Heading test](#heading-test)
- [Head test 2](#head-test-2)

# Heading test

content

## Head test 2

test content

**Comment by MelleDijkstra** [comment]
This is a pretty cool feature. I use the Typora application for writing my markdown which also supports this.
