### ISSUE TITLE
TypeError: url.indexOf is not a function

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-markdown#62]
I am getting this error since I updated to jQuery 3.0+

The problem is in [this line](https://github.com/kartik-v/yii2-markdown/blob/42dc1b2461aa5d3da29583b81db3e10f95752de4/MarkdownEditor.php#L537).

See solution: https://stackoverflow.com/questions/37738732/jquery-3-0-url-indexof-error

**Comment by fedornabilkin** [comment]
Такая же проблема возникла после обновления Yii2 до версии 2.0.14.1

**Comment by vercotux** [comment]
Looks like this is fixed by pull request #57 
@kartik-v could you please have a look. It is a very critical problem.

**Comment by kartik-v** [comment]
PR #57 is merged.

**Comment by vercotux** [comment]
Thank you!
