### ISSUE TITLE
Error when using <?php tag inside the processing text

### ISSUE THREAD

**Issue by buttflattery** [kartik-v/yii2-markdown#72]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-markdown.
- [x] This is not a usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/markdown) and [demos](http://demos.krajee.com/markdown-demo).
- [x] This is not a general programming/coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Install the extension
2.crate a readme.md file and add the following containing the `<?php` tag
```

<?php echo "some text"

```
3. Convert the text using

```
echo Markdown::process($this->render('README.md'));
```

## Expected behavior and actual behavior

When I follow those steps, I see...

> PHP Parse Error – yii\base\ErrorException
> syntax error, unexpected '`'

I was expecting...
The formatted output 

If you remove the `<?php` tag from the text to be processed then it works ok

**BUT**

If you use it in the following way it even works **along the `<?php`** tag

```
<?php $html = <<< HTML
        <?php echo "some text";
HTML;
?>
<?=\kartik\markdown\Markdown::process($html) ?>
```

## Environment
Yii 2.0.15.1

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-markdown version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/markdown-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-markdown without other plugins.

**Comment by kartik-v** [comment]
Use `Html::encode` on the text before you process using `Markdown::process`.

**Comment by buttflattery** [comment]
@kartik-v Well to my surprise the `Html::encode()` does not solve the issue, instead you have to provide the closing `?>` tags along with the starting tags to make it work correctly.
